services:
  - type: web
    name: taller-ceramica-hores
    env: python
    plan: free
    buildCommand: "npm install --omit=dev || true"
    startCommand: python3 server.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
